/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.93.0
  Forc version: 0.62.0
  Fuel-Core version: 0.31.0
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Option, Enum, Vec } from "./common";

export enum AuthErrorInput { Unauthorized = 'Unauthorized' };
export enum AuthErrorOutput { Unauthorized = 'Unauthorized' };
export enum OrderbookErrorInput { MarketAlreadyRegistered = 'MarketAlreadyRegistered', MarketNotRegistered = 'MarketNotRegistered' };
export enum OrderbookErrorOutput { MarketAlreadyRegistered = 'MarketAlreadyRegistered', MarketNotRegistered = 'MarketNotRegistered' };

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type AssetIdInput = { bits: string };
export type AssetIdOutput = AssetIdInput;
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type MarketRegisterEventInput = { asset_id: AssetIdInput, market: ContractIdInput };
export type MarketRegisterEventOutput = { asset_id: AssetIdOutput, market: ContractIdOutput };
export type MarketUnregisterEventInput = { asset_id: AssetIdInput };
export type MarketUnregisterEventOutput = { asset_id: AssetIdOutput };

export type OrderbookContractAbiConfigurables = Partial<{
  OWNER: AddressInput;
}>;

export interface OrderbookContractAbiInterface extends Interface {
  functions: {
    config: FunctionFragment;
    register_market: FunctionFragment;
    registered_markets: FunctionFragment;
    unregister_market: FunctionFragment;
  };
}

export class OrderbookContractAbi extends Contract {
  interface: OrderbookContractAbiInterface;
  functions: {
    config: InvokeFunction<[], AddressOutput>;
    register_market: InvokeFunction<[asset_id: AssetIdInput, market: ContractIdInput], void>;
    registered_markets: InvokeFunction<[asset_ids: Vec<AssetIdInput>], Vec<[AssetIdOutput, Option<ContractIdOutput>]>>;
    unregister_market: InvokeFunction<[asset_id: AssetIdInput], void>;
  };
}
