/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.93.0
  Forc version: 0.62.0
  Fuel-Core version: 0.31.0
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Option, Enum, Vec } from "./common";

export enum AuthErrorInput { Unauthorized = 'Unauthorized' };
export enum AuthErrorOutput { Unauthorized = 'Unauthorized' };
export enum OrderbookErrorInput { MarketAlreadyRegistered = 'MarketAlreadyRegistered', MarketNotRegistered = 'MarketNotRegistered' };
export enum OrderbookErrorOutput { MarketAlreadyRegistered = 'MarketAlreadyRegistered', MarketNotRegistered = 'MarketNotRegistered' };

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type AssetIdInput = { bits: string };
export type AssetIdOutput = AssetIdInput;
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type MarketRegisterEventInput = { base: AssetIdInput, quote: AssetIdInput, market: ContractIdInput };
export type MarketRegisterEventOutput = { base: AssetIdOutput, quote: AssetIdOutput, market: ContractIdOutput };
export type MarketUnregisterEventInput = { base: AssetIdInput, quote: AssetIdInput, market: ContractIdInput };
export type MarketUnregisterEventOutput = { base: AssetIdOutput, quote: AssetIdOutput, market: ContractIdOutput };

export type OrderbookContractAbiConfigurables = Partial<{
  OWNER: AddressInput;
  VERSION: BigNumberish;
}>;

export interface OrderbookContractAbiInterface extends Interface {
  functions: {
    config: FunctionFragment;
    markets: FunctionFragment;
    register_market: FunctionFragment;
    unregister_market: FunctionFragment;
  };
}

export class OrderbookContractAbi extends Contract {
  interface: OrderbookContractAbiInterface;
  functions: {
    config: InvokeFunction<[], [AddressOutput, number]>;
    markets: InvokeFunction<[market_assets: Vec<[AssetIdInput, AssetIdInput]>], Vec<[AssetIdOutput, AssetIdOutput, Option<ContractIdOutput>]>>;
    register_market: InvokeFunction<[market: ContractIdInput], void>;
    unregister_market: InvokeFunction<[market: ContractIdInput], void>;
  };
}
