/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.84.0
  Forc version: 0.56.0
  Fuel-Core version: 0.26.0
*/

export type { MarketAbi } from './MarketAbi';

export { MarketAbi__factory } from './factories/MarketAbi__factory';
