/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.79.0
  Forc version: 0.49.3
  Fuel-Core version: 0.22.1
*/

export type { ClearingHouseAbi } from './ClearingHouseAbi';

export { ClearingHouseAbi__factory } from './factories/ClearingHouseAbi__factory';
