/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.84.0
  Forc version: 0.56.0
  Fuel-Core version: 0.26.0
*/

export type { PythContractAbi } from './PythContractAbi';

export { PythContractAbi__factory } from './factories/PythContractAbi__factory';
