/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.93.0
  Forc version: 0.62.0
  Fuel-Core version: 0.31.0
*/

export type { MultiassetContractAbi } from './MultiassetContractAbi';

export { MultiassetContractAbi__factory } from './factories/MultiassetContractAbi__factory';
