/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.93.0
  Forc version: 0.62.0
  Fuel-Core version: 0.31.0
*/

export type { SparkMarketAbi } from './SparkMarketAbi';

export { SparkMarketAbi__factory } from './factories/SparkMarketAbi__factory';
