/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.2
  Forc version: 0.60.0
  Fuel-Core version: 0.27.0
*/

export type { MarketContractAbi } from './MarketContractAbi';

export { MarketContractAbi__factory } from './factories/MarketContractAbi__factory';
