/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.90.0
  Forc version: 0.60.0
  Fuel-Core version: 0.30.0
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Vec } from "./common";

export type AssetIdInput = { bits: string };
export type AssetIdOutput = AssetIdInput;
export type I64Input = { value: BigNumberish, negative: boolean };
export type I64Output = { value: BN, negative: boolean };

export type FulfillScriptAbiConfigurables = {
  ORDER_BOOK_CONTRACT_ID: string;
};

interface FulfillScriptAbiInterface extends Interface {
  functions: {
    main: FunctionFragment;
  };
}

export class FulfillScriptAbi extends Contract {
  interface: FulfillScriptAbiInterface;
  functions: {
    main: InvokeFunction<[orders: Vec<string>, price: BigNumberish, base_token: AssetIdInput, base_size: I64Input], void>;
  };
}
