/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.84.0
  Forc version: 0.56.0
  Fuel-Core version: 0.26.0
*/

import { Interface, Contract, ContractFactory } from "fuels";
import type { Provider, Account, AbstractAddress, BytesLike, DeployContractOptions, StorageSlot } from "fuels";
import type { ScriptProxyAbi, ScriptProxyAbiInterface } from "../ScriptProxyAbi";

const _abi = {
  "types": [
    {
      "typeId": 0,
      "type": "()",
      "components": [],
      "typeParameters": null
    },
    {
      "typeId": 1,
      "type": "b256",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 2,
      "type": "bool",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 3,
      "type": "enum Method",
      "components": [
        {
          "name": "OpenOrder",
          "type": 14,
          "typeArguments": null
        },
        {
          "name": "MatchOrders",
          "type": 13,
          "typeArguments": null
        },
        {
          "name": "FulfillOrder",
          "type": 9,
          "typeArguments": null
        },
        {
          "name": "WithdrawAll",
          "type": 18,
          "typeArguments": null
        },
        {
          "name": "WithdrawCollateral",
          "type": 19,
          "typeArguments": null
        },
        {
          "name": "Liquidate",
          "type": 11,
          "typeArguments": null
        },
        {
          "name": "LiquidateCollateral",
          "type": 12,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 4,
      "type": "generic T",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 5,
      "type": "raw untyped ptr",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 6,
      "type": "struct Address",
      "components": [
        {
          "name": "value",
          "type": 1,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 7,
      "type": "struct AssetId",
      "components": [
        {
          "name": "value",
          "type": 1,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 8,
      "type": "struct Bytes",
      "components": [
        {
          "name": "buf",
          "type": 15,
          "typeArguments": null
        },
        {
          "name": "len",
          "type": 20,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 9,
      "type": "struct FulfillOrder",
      "components": [
        {
          "name": "clearing_house",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "base_size",
          "type": 10,
          "typeArguments": null
        },
        {
          "name": "order_id",
          "type": 1,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 10,
      "type": "struct I64",
      "components": [
        {
          "name": "value",
          "type": 20,
          "typeArguments": null
        },
        {
          "name": "negative",
          "type": 2,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 11,
      "type": "struct Liquidate",
      "components": [
        {
          "name": "clearing_house",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "trader",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "base_token",
          "type": 7,
          "typeArguments": null
        },
        {
          "name": "position_size_to_be_liquidated",
          "type": 10,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 12,
      "type": "struct LiquidateCollateral",
      "components": [
        {
          "name": "vault",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "trader",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "base_token",
          "type": 7,
          "typeArguments": null
        },
        {
          "name": "settlement_amount",
          "type": 20,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 13,
      "type": "struct MatchOrders",
      "components": [
        {
          "name": "clearing_house",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "order_sell_id",
          "type": 1,
          "typeArguments": null
        },
        {
          "name": "order_buy_id",
          "type": 1,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 14,
      "type": "struct OpenOrder",
      "components": [
        {
          "name": "clearing_house",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "base_token",
          "type": 7,
          "typeArguments": null
        },
        {
          "name": "base_size",
          "type": 10,
          "typeArguments": null
        },
        {
          "name": "order_price",
          "type": 20,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 15,
      "type": "struct RawBytes",
      "components": [
        {
          "name": "ptr",
          "type": 5,
          "typeArguments": null
        },
        {
          "name": "cap",
          "type": 20,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 16,
      "type": "struct RawVec",
      "components": [
        {
          "name": "ptr",
          "type": 5,
          "typeArguments": null
        },
        {
          "name": "cap",
          "type": 20,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        4
      ]
    },
    {
      "typeId": 17,
      "type": "struct Vec",
      "components": [
        {
          "name": "buf",
          "type": 16,
          "typeArguments": [
            {
              "name": "",
              "type": 4,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "len",
          "type": 20,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        4
      ]
    },
    {
      "typeId": 18,
      "type": "struct WithdrawAll",
      "components": [
        {
          "name": "vault",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "collateral",
          "type": 7,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 19,
      "type": "struct WithdrawCollateral",
      "components": [
        {
          "name": "vault",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "amount",
          "type": 20,
          "typeArguments": null
        },
        {
          "name": "collateral",
          "type": 7,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 20,
      "type": "u64",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "method",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "proxy",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "fee",
          "type": 20,
          "typeArguments": null
        },
        {
          "name": "price_feed_ids",
          "type": 17,
          "typeArguments": [
            {
              "name": "",
              "type": 1,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "price_update_data",
          "type": 17,
          "typeArguments": [
            {
              "name": "",
              "type": 8,
              "typeArguments": null
            }
          ]
        }
      ],
      "name": "main",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "payable",
          "arguments": []
        }
      ]
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const _storageSlots: StorageSlot[] = [];

export class ScriptProxyAbi__factory {
  static readonly abi = _abi;

  static readonly storageSlots = _storageSlots;

  static createInterface(): ScriptProxyAbiInterface {
    return new Interface(_abi) as unknown as ScriptProxyAbiInterface
  }

  static connect(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider
  ): ScriptProxyAbi {
    return new Contract(id, _abi, accountOrProvider) as unknown as ScriptProxyAbi
  }

  static async deployContract(
    bytecode: BytesLike,
    wallet: Account,
    options: DeployContractOptions = {}
  ): Promise<ScriptProxyAbi> {
    const factory = new ContractFactory(bytecode, _abi, wallet);

    const { storageSlots } = ScriptProxyAbi__factory;

    const contract = await factory.deployContract({
      storageSlots,
      ...options,
    });

    return contract as unknown as ScriptProxyAbi;
  }
}
