/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.94.8
*/

export { SparkRegistry } from './SparkRegistry';
export { SparkRegistryFactory } from './SparkRegistryFactory';
